version: "2"
services:
  plone:
    image: plone:4
    ports:
      - "8080"
    volumes:
      - ../../:/plone/instance/src/eea.plotly
    environment:
      ADDONS: "eea.plotly[test]"
      DEVELOP: "src/eea.plotly"
